name: github_archive
version: 1.0.0
config-version: 2

profile: github_archive

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

vars:
  use_local_seed: true

seeds:
  github_archive:
    raw_github_events:
      +column_types:
        id: varchar
        type: varchar
        created_at: varchar
        actor_login: varchar
        actor_id: varchar
        repo_name: varchar
        repo_id: varchar
        payload: varchar

models:
  github_archive:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
